USE [master]
GO

-- Create database
CREATE DATABASE [nightingale-id]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nightingale-id', FILENAME = N'/var/opt/mssql/data/nightingale-id.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'nightingale-id_log', FILENAME = N'/var/opt/mssql/data/nightingale-id_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [nightingale-id] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nightingale-id].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nightingale-id] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nightingale-id] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nightingale-id] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nightingale-id] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nightingale-id] SET ARITHABORT OFF 
GO

ALTER DATABASE [nightingale-id] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nightingale-id] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nightingale-id] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [nightingale-id] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nightingale-id] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nightingale-id] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nightingale-id] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nightingale-id] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nightingale-id] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nightingale-id] SET  DISABLE_BROKER 
GO

ALTER DATABASE [nightingale-id] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nightingale-id] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nightingale-id] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nightingale-id] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nightingale-id] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nightingale-id] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nightingale-id] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nightingale-id] SET RECOVERY FULL 
GO

ALTER DATABASE [nightingale-id] SET  MULTI_USER 
GO

ALTER DATABASE [nightingale-id] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nightingale-id] SET DB_CHAINING OFF 
GO

ALTER DATABASE [nightingale-id] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [nightingale-id] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [nightingale-id] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [nightingale-id] SET QUERY_STORE = OFF
GO

USE [nightingale-id]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [nightingale-id] SET  READ_WRITE 
GO

-- Create login
USE [master]
GO 

CREATE LOGIN [NightingaleId] WITH PASSWORD=N'NotForPr0duction!!', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

-- Map login to ID database & grant permissions
USE [nightingale-id]
GO

CREATE USER [NightingaleId] FOR LOGIN [NightingaleId] WITH DEFAULT_SCHEMA=[dbo]
GO

EXEC sp_addrolemember N'db_owner', N'NightingaleId'
GO

GRANT CREATE TABLE TO [NightingaleId]
GO

EXEC sp_configure 'remote access', 1 ;  
GO  
RECONFIGURE ;  
GO